<a href="https://colab.research.google.com/github/Jaspreet-Singh619/Numpy/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
my_array = np.array((1, "hi"))


In [6]:
print(my_array.dtype)

<U53


In [5]:
my_array = np.array((1, "hiwbchjdbwjcbhjchebcechjehjcberhjvbejvbehjvevcervevef"))


In [7]:
list_2d = [[1, 2], [3, 4], [5, 6]]
list_2d

[[1, 2], [3, 4], [5, 6]]

In [8]:
array_2d=np.array(list_2d)

In [9]:
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
array_2d.dtype

dtype('int64')

In [11]:
np.arange(0, 11, 2)  # step by 2 from 1 to 11

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.linspace(0, 10, 5)  # 5 equally spaced points between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
array_2d_zero=np.zeros((2, 3))  # an array of zeros with size 2 x 3

In [14]:
array_2d_zero.dtype

dtype('float64')

In [15]:
array_2d_zero.astype(int)

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
array_2d_rand=np.random.rand(5, 2)  # random numbers uniformly distributed from 0 to 1 with size 5 x 2

In [22]:
array_2d_rand.size

10

In [27]:
array_2d = np.ones((3, 2)).astype(int)
print(array_2d)

[[1 1]
 [1 1]
 [1 1]]


In [28]:
array_2d=np.zeros((2,2)).astype(int)

In [32]:
print(array_2d)

[[1.]
 [1.]
 [1.]
 [1.]]


In [31]:
array_2d=np.ones((4,1))

In [34]:
np.ones((3,2)).astype(int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [4]:
cost = np.array([20, 15, 25])
print("Pie cost:")
print(cost)
sales = np.array([[2, 3, 1], [6, 3, 3], [5, 3, 5]])
print("\nPie sales (#):")
print(sales)

Pie cost:
[20 15 25]

Pie sales (#):
[[2 3 1]
 [6 3 3]
 [5 3 5]]


In [36]:
print(sales*cost)

[[ 40  45  25]
 [120  45  75]
 [100  45 125]]


In [8]:
cost_broad=np.repeat(cost,3)

In [10]:
cost_broad.reshape(3,3)

array([[20, 20, 20],
       [15, 15, 15],
       [25, 25, 25]])

In [11]:
array_1d=np.ones(3)

In [12]:
array_1d.shape

(3,)

In [13]:
array_1d

array([1., 1., 1.])

In [16]:
print(array_1d[:, None])

[[1.]
 [1.]
 [1.]]


In [19]:
x=np.random.randint(0,9,(5,2))

In [21]:
x.ravel()

array([0, 4, 2, 0, 6, 0, 2, 2, 3, 2])

In [22]:
x.reshape(x.size,1)

array([[0],
       [4],
       [2],
       [0],
       [6],
       [0],
       [2],
       [2],
       [3],
       [2]])

In [25]:
x=x.transpose((1,x.size))

AxisError: axis 10 is out of bounds for array of dimension 2

In [24]:
x

array([[0, 2, 6, 2, 3],
       [4, 0, 0, 2, 2]])

In [26]:
list=[]
for i in range(10):
  list.append(i)

In [27]:
list.append(9)

In [28]:
x=np.array(list)

In [29]:
import scipy.stats as stats

In [30]:
print(stats.mode(x))

ModeResult(mode=9, count=2)
